#!/usr/bin/env node
import { remoteEnvironment as productRemoteEnvironment } from '../../../build.mjs';
if(process.env.GITHUB_ACTIONS==='true'&&String(process.env.GITHUB_WORKFLOW||'').startsWith('tuyubooking.'))Object.assign(process.env,productRemoteEnvironment());
// RELEASE_BUILD: full; CARGO_INCREMENTAL=0
// TUYUBOOKING_APP_ROOT_CONTRACT: 主机端 Release 显式选择 tuyubooking/app 的主机入口。
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { preparePostgresRuntime } from '../../postgres-runtime.mjs';
const identity = Object.freeze({ product: 'tuyubooking', platform: 'host-macos', prefix: 'tuyubooking-host-macos-v', ciTitle: '途遇商家端 · 主机 macOS · CI', workflow: 'tuyubooking.host-macos.release', artifact: 'tuyubooking-host-macos.zip' });
const root = process.cwd(); const output = join(process.env.RUNNER_TEMP || '/tmp', 'tuyubooking-host-release');
function required(value, message) { if (!value) throw new Error(message); }
function parseVersion(value) { const match = /^(0|[1-9]\d*)\.(0|[1-9]\d{0,1})\.(0|[1-9]\d{0,1})$/.exec(value || ''); required(match, 'macOS 软件版本无效'); return match.slice(1).map(Number); }
function githubJSON(args) { return JSON.parse(execFileSync('gh', args, { encoding: 'utf8', env: process.env })); }
function run(file, args, cwd = root) { execFileSync(file, args, { cwd, stdio: 'inherit', env: process.env }); }
function hash(path) { return createHash('sha256').update(readFileSync(path)).digest('hex'); }
function inputs() { const value = { repository: process.env.GITHUB_REPOSITORY, source: process.env.SOURCE_SHA, ciRunID: process.env.CI_RUN_ID, version: process.env.SOFTWARE_VERSION, tag: process.env.VERSION_TAG }; required(value.repository === 'tuyutata/tuyubooking', '途遇商家仓库身份无效'); required(/^[0-9a-f]{40}$/u.test(value.source || ''), 'macOS Release 源提交无效'); required(/^[1-9][0-9]*$/u.test(value.ciRunID || ''), 'macOS CI Run ID 无效'); required(/^\d+\.\d{1,2}\.\d{1,2}$/u.test(value.version || ''), 'macOS 版本无效'); required(value.tag === `${identity.prefix}${value.version}`, 'macOS Tag 无效'); return value; }
function verify(value) { required(process.platform === 'darwin' && process.arch === 'arm64', '途遇商家主机端 macOS Release 必须运行在 ARM64'); required(execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim() === value.source, 'macOS 源码提交不一致'); const runInfo = githubJSON(['api', `repos/${value.repository}/actions/runs/${value.ciRunID}`]); required(String(runInfo?.id) === value.ciRunID && runInfo?.head_sha === value.source && runInfo?.head_branch === 'main' && runInfo?.event === 'workflow_dispatch' && runInfo?.status === 'completed' && runInfo?.conclusion === 'success' && String(runInfo?.display_title || '') === identity.ciTitle && String(runInfo?.path || '').endsWith('/tuyubooking-host-macos-ci.yml'), 'macOS CI Run 身份不一致'); required(spawnSync('gh', ['release', 'view', value.tag, '--repo', value.repository], { stdio: 'ignore' }).status !== 0, 'macOS 正式 Release 已存在，禁止覆盖'); }
function context(value) { writeFileSync('release-context.json', `${JSON.stringify({ repository: value.repository, product_id: identity.product, platform: identity.platform, software_flow: 'release', software_version: value.version, version_tag: value.tag, source_sha: value.source, ci_run_id: Number(value.ciRunID), workflow: identity.workflow }, null, 2)}\n`); }
function manifest(value) { const asset = join(output, identity.artifact); required(existsSync(asset), 'macOS 正式资产不存在'); const body = { product_id: identity.product, platform: identity.platform, software_version: value.version, git_commit_sha: value.source, ci_run_id: Number(value.ciRunID), assets: [{ name: identity.artifact, sha256: hash(asset) }] }; const manifestPath = join(output, 'release-manifest.json'); writeFileSync(manifestPath, `${JSON.stringify(body, null, 2)}\n`); writeFileSync(join(output, 'SHA256SUMS'), `${[`${hash(asset)}  ${identity.artifact}`, `${hash(manifestPath)}  release-manifest.json`].sort().join('\n')}\n`); }
async function build(value) { verify(value); mkdirSync(output); run('git', ['submodule', 'status', '--recursive']); const work = join(output, 'work'); mkdirSync(work); process.env.TUYUBOOKING_ROOT = root; process.env.CARGO_TARGET_DIR = join(work, 'cargo'); const sourceApp = join(root, 'app'); const application = execFileSync(process.execPath, [join(sourceApp, 'scripts/project.mjs'), 'create', '--source-root', sourceApp, '--work-root', work, '--platform', 'macos'], { encoding: 'utf8', env: process.env }).trim(); run('flutter', ['pub', 'get', '--enforce-lockfile'], application); run(process.execPath, [join(sourceApp, 'scripts/project.mjs'), 'native', '--source-root', sourceApp, '--work-root', work, '--output', application, '--platform', 'macos']); process.env.TUYU_POSTGRES_BIN = await preparePostgresRuntime('macos', work); run('cargo', ['test', '--workspace', '--locked'], root); run('cargo', ['build', '--release', '--locked', '-p', 'tuyubooking-native'], root); run('flutter', ['build', 'macos', '--release', '--target', 'lib/main_host.dart', `--build-name=${value.version}`, '--dart-define=TUYU_SERVE_URL=https://serve.tuyulove.com'], application); const products = join(application, 'build/macos/Build/Products/Release'); const appNames = readdirSync(products).filter((name) => name.endsWith('.app')); required(appNames.length === 1, 'macOS Release App 数量无效'); const app = join(products, appNames[0]); cpSync(dirname(process.env.TUYU_POSTGRES_BIN), join(app, 'Contents/Resources/postgresql'), { recursive: true }); const executableName = execFileSync('/usr/libexec/PlistBuddy', ['-c', 'Print :CFBundleExecutable', join(app, 'Contents/Info.plist')], { encoding: 'utf8' }).trim(); const executable = join(app, 'Contents/MacOS', executableName); const librarySource = join(process.env.CARGO_TARGET_DIR, 'release/libtuyubooking_native.dylib'); required(existsSync(executable) && existsSync(librarySource), 'macOS 原生二进制未生成'); required(execFileSync('lipo', ['-archs', executable], { encoding: 'utf8' }).trim() === 'arm64', 'macOS App 不是纯 ARM64'); required(execFileSync('lipo', ['-archs', librarySource], { encoding: 'utf8' }).trim() === 'arm64', 'macOS Rust 动态库不是纯 ARM64'); const frameworks = join(app, 'Contents/Frameworks'); mkdirSync(frameworks, { recursive: true }); cpSync(librarySource, join(frameworks, 'libtuyubooking_native.dylib')); run('codesign', ['--force', '--deep', '--sign', '-', app]); run('codesign', ['--verify', '--deep', '--strict', app]); run('ditto', ['-c', '-k', '--keepParent', app, join(output, identity.artifact)]); manifest(value); }
function publish(value) { run('gh', ['release', 'create', value.tag, '--repo', value.repository, '--title', `途遇商家主机端 macOS ${value.version}`, '--notes', `SOURCE_SHA:${value.source}`, ...[identity.artifact, 'release-manifest.json', 'SHA256SUMS'].map((name) => join(output, name))]); }
try { const command = process.argv[2]; const value = inputs(); if (command === 'verify-release-source') verify(value); else if (command === 'write-context') context(value); else if (command === 'build-release') await build(value); else if (command === 'publish-release') publish(value); else throw new Error(`macOS Release 子命令未登记：${command || '(empty)'}`); } catch (error) { console.error(error.message); process.exitCode = 1; }
