#!/usr/bin/env node
import { remoteEnvironment as productRemoteEnvironment } from '../../../build.mjs';
if(process.env.GITHUB_ACTIONS==='true'&&String(process.env.GITHUB_WORKFLOW||'').startsWith('tuyubooking.'))Object.assign(process.env,productRemoteEnvironment());
// RELEASE_BUILD: full; CARGO_INCREMENTAL=0
// TUYUBOOKING_APP_ROOT_CONTRACT: 主机端 Release 只使用途遇商家主机端打包入口。
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const identity = Object.freeze({ product: 'tuyubooking', platform: 'host-linux-amd', prefix: 'tuyubooking-host-linux-amd-v', ciTitle: '途遇商家端 · 主机 LinuxAMD · CI', workflow: 'tuyubooking.host-linux-amd.release', artifact: 'TuyuBookingHost-LinuxAMD.deb' });
const root = process.cwd(); const output = join(process.env.RUNNER_TEMP || '/tmp', 'tuyubooking-host-release');
function required(value, message) { if (!value) throw new Error(message); }
function parseVersion(value) { const match = /^(0|[1-9]\d*)\.(0|[1-9]\d{0,1})\.(0|[1-9]\d{0,1})$/.exec(value || ''); required(match, 'Linux 软件版本无效'); return match.slice(1).map(Number); }
function githubJSON(args) { return JSON.parse(execFileSync('gh', args, { encoding: 'utf8', env: process.env })); }
function run(file, args, cwd = root, extraEnv = {}) { execFileSync(file, args, { cwd, stdio: 'inherit', env: { ...process.env, ...extraEnv } }); }
function hash(path) { return createHash('sha256').update(readFileSync(path)).digest('hex'); }
function inputs() { const value = { repository: process.env.GITHUB_REPOSITORY, source: process.env.SOURCE_SHA, ciRunID: process.env.CI_RUN_ID, version: process.env.SOFTWARE_VERSION, tag: process.env.VERSION_TAG }; required(value.repository === 'tuyutata/tuyubooking', '途遇商家仓库身份无效'); required(/^[0-9a-f]{40}$/u.test(value.source || ''), 'Linux Release 源提交无效'); required(/^[1-9][0-9]*$/u.test(value.ciRunID || ''), 'Linux CI Run ID 无效'); required(/^\d+\.\d{1,2}\.\d{1,2}$/u.test(value.version || ''), 'Linux 版本无效'); required(value.tag === `${identity.prefix}${value.version}`, 'Linux Tag 无效'); return value; }
function verify(value) {
  required(process.platform === 'linux' && process.arch === 'x64', '途遇商家主机端 Linux Release 必须运行在 AMD64');
  required(execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim() === value.source, 'Linux 源码提交不一致'); const runInfo = githubJSON(['api', `repos/${value.repository}/actions/runs/${value.ciRunID}`]); required(String(runInfo?.id) === value.ciRunID && runInfo?.head_sha === value.source && runInfo?.head_branch === 'main' && runInfo?.event === 'workflow_dispatch' && runInfo?.status === 'completed' && runInfo?.conclusion === 'success' && String(runInfo?.display_title || '') === identity.ciTitle && String(runInfo?.path || '').endsWith('/tuyubooking-host-linux-amd-ci.yml'), 'Linux CI Run 身份不一致'); required(spawnSync('gh', ['release', 'view', value.tag, '--repo', value.repository], { stdio: 'ignore' }).status !== 0, 'Linux 正式 Release 已存在，禁止覆盖'); }
function context(value) { writeFileSync('release-context.json', `${JSON.stringify({ repository: value.repository, product_id: identity.product, platform: identity.platform, software_flow: 'release', software_version: value.version, version_tag: value.tag, source_sha: value.source, ci_run_id: Number(value.ciRunID), workflow: identity.workflow }, null, 2)}\n`); }
function manifest(value) { const asset = join(output, identity.artifact); required(existsSync(asset), 'Linux 正式资产不存在'); const body = { product_id: identity.product, platform: identity.platform, software_version: value.version, git_commit_sha: value.source, ci_run_id: Number(value.ciRunID), assets: [{ name: identity.artifact, sha256: hash(asset) }] }; const manifestPath = join(output, 'release-manifest.json'); writeFileSync(manifestPath, `${JSON.stringify(body, null, 2)}\n`); writeFileSync(join(output, 'SHA256SUMS'), `${[`${hash(asset)}  ${identity.artifact}`, `${hash(manifestPath)}  release-manifest.json`].sort().join('\n')}\n`); }
function build(value) { verify(value); mkdirSync(output); run('git', ['submodule', 'status', '--recursive']); run('bash', ['scripts/linux-amd/verify_source.sh'], root); run('bash', ['scripts/linux-amd/build_package.sh'], root, { TUYUBOOKING_WORK_DIR: join(output, 'work'), TUYU_SERVE_URL: 'https://serve.tuyulove.com', TUYU_BOOKING_VERSION: value.version }); const source = join(output, 'work', 'TuyuBooking-LinuxAMD.deb'); required(existsSync(source), 'Linux AMD64 Debian 正式包未生成'); run('dpkg-deb', ['--field', source, 'Architecture']); required(execFileSync('dpkg-deb', ['--field', source, 'Architecture'], { encoding: 'utf8' }).trim() === 'amd64', 'Linux 正式包不是 AMD64'); cpSync(source, join(output, identity.artifact)); manifest(value); }
function publish(value) { run('gh', ['release', 'create', value.tag, '--repo', value.repository, '--title', `途遇商家主机端 Linux ${value.version}`, '--notes', `SOURCE_SHA:${value.source}`, ...[identity.artifact, 'release-manifest.json', 'SHA256SUMS'].map((name) => join(output, name))]); }
try { const command = process.argv[2]; const value = inputs(); if (command === 'verify-release-source') verify(value); else if (command === 'write-context') context(value); else if (command === 'build-release') build(value); else if (command === 'publish-release') publish(value); else throw new Error(`Linux Release 子命令未登记：${command || '(empty)'}`); } catch (error) { console.error(error.message); process.exitCode = 1; }
