#!/usr/bin/env node
// RELEASE_BUILD: full; CARGO_INCREMENTAL=0；正式包固定使用分机端入口。
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const identity = Object.freeze({ product: 'tuyubooking', platform: 'client-windows', prefix: 'tuyubooking-client-windows-v', ciTitle: '途遇商家端 · 分机 Windows · CI', workflow: 'tuyubooking.client-windows.release', artifact: 'tuyubooking-client-windows.zip' });
const root = process.cwd(); const output = join(process.env.RUNNER_TEMP || process.env.TEMP, 'tuyubooking-client-release');
function required(value, message) { if (!value) throw new Error(message); }
function run(file, args, cwd = root) { execFileSync(file, args, { cwd, stdio: 'inherit', env: process.env }); }
function hash(path) { return createHash('sha256').update(readFileSync(path)).digest('hex'); }
function inputs() { const value = { repository: process.env.GITHUB_REPOSITORY, source: process.env.SOURCE_SHA, ciRunID: process.env.CI_RUN_ID, version: process.env.SOFTWARE_VERSION, tag: process.env.VERSION_TAG }; required(value.repository === 'tuyutata/tuyubooking', '途遇商家仓库身份无效'); required(/^[0-9a-f]{40}$/u.test(value.source || ''), 'Windows Release 源提交无效'); required(/^[1-9][0-9]*$/u.test(value.ciRunID || ''), 'Windows CI Run ID 无效'); required(/^\d+\.\d{1,2}\.\d{1,2}$/u.test(value.version || ''), 'Windows 版本无效'); required(value.tag === `${identity.prefix}${value.version}`, 'Windows Tag 无效'); return value; }
function verify(value) { required(process.platform === 'win32' && process.arch === 'x64', '途遇商家分机端 Windows Release 必须运行在 x86-64'); required(execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim() === value.source, 'Windows 源码提交不一致'); const info = JSON.parse(execFileSync('gh', ['api', `repos/${value.repository}/actions/runs/${value.ciRunID}`], { encoding: 'utf8', env: process.env })); required(String(info?.id) === value.ciRunID && info?.head_sha === value.source && info?.head_branch === 'main' && info?.event === 'workflow_dispatch' && info?.status === 'completed' && info?.conclusion === 'success' && String(info?.display_title || '') === identity.ciTitle && String(info?.path || '').endsWith('/tuyubooking-client-windows-ci.yml'), 'Windows CI Run 身份不一致'); required(spawnSync('gh', ['release', 'view', value.tag, '--repo', value.repository], { stdio: 'ignore' }).status !== 0, 'Windows 正式 Release 已存在，禁止覆盖'); }
function manifest(value) { const asset = join(output, identity.artifact); required(existsSync(asset), 'Windows 正式资产不存在'); const body = { product_id: identity.product, platform: identity.platform, software_version: value.version, git_commit_sha: value.source, ci_run_id: Number(value.ciRunID), assets: [{ name: identity.artifact, sha256: hash(asset) }] }; const path = join(output, 'release-manifest.json'); writeFileSync(path, `${JSON.stringify(body, null, 2)}\n`); writeFileSync(join(output, 'SHA256SUMS'), `${hash(asset)}  ${identity.artifact}\n${hash(path)}  release-manifest.json\n`); }
function build(value) { verify(value); rmSync(output, { recursive: true, force: true }); mkdirSync(output, { recursive: true }); run('flutter', ['pub', 'get', '--enforce-lockfile'], join(root, 'app')); run('flutter', ['test'], join(root, 'app')); run('flutter', ['build', 'windows', '--release', '--target', 'lib/main_client.dart', `--build-name=${value.version}`], join(root, 'app')); const bundle = join(root, 'app/build/windows/x64/runner/Release'); required(existsSync(bundle), 'Windows 分机端正式目录不存在'); run('powershell', ['-NoProfile', '-NonInteractive', '-Command', `Compress-Archive -Path '${bundle}\\*' -DestinationPath '${join(output, identity.artifact)}' -CompressionLevel Optimal`]); manifest(value); }
function publish(value) { run('gh', ['release', 'create', value.tag, '--repo', value.repository, '--title', `途遇商家分机端 Windows ${value.version}`, '--notes', `SOURCE_SHA:${value.source}`, ...[identity.artifact, 'release-manifest.json', 'SHA256SUMS'].map((name) => join(output, name))]); }
try { const value = inputs(); const command = process.argv[2]; if (command === 'build-release') build(value); else if (command === 'publish-release') publish(value); else if (command === 'verify-release-source') verify(value); else throw new Error(`Windows Release 子命令未登记：${command || '(empty)'}`); } catch (error) { console.error(error.message); process.exitCode = 1; }
